import Footer from "@/components/Footer";
import "../styles/style.scss";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "WatchTime shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Toaster />
          <Navbar />
          <div className="container">{children}</div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
